name: Publish to Modrinth

on:
  push:
    tags:
      - "v*"   # ex: v1.2.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: CqxOjE5k
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          version-type: alpha
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
          # auto detect verions
